# Use lightweight python image
FROM python:3.11-slim

# Set working directory
WORKDIR /frontend

COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy streamlit app
COPY . .

# Expose streamlit default port
EXPOSE 8501

# Run streamlit app
CMD [ "streamlit", "run", "streamlit_app.py", "--server.port=8501", "--server.address=0.0.0.0"]